from pptx import Presentation
from pptx.util import Inches, Pt
import os
import requests
from io import BytesIO

def save_as_ppt(data: dict, output_folder="output"):
    if "error" in data:
        raise ValueError(f"Cannot create PPT: {data['error']}")
        
    topic = data.get("title", "Generated_Topic")
    os.makedirs(output_folder, exist_ok=True)
    ppt_path = os.path.join(output_folder, f"{topic.replace(' ', '_')}.pptx")

    prs = Presentation()

    # Title Slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = topic
    slide.placeholders[1].text = "A Presentation Generated by Gemini AI"

    # Summary Slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Key Takeaways / Summary"
    tf = slide.placeholders[1].text_frame
    tf.text = ""
    for point in data.get("summary_points", []):
        p = tf.add_paragraph()
        p.text = point
        p.level = 0
        p.font.size = Pt(20)

    # Main Content Slides
    for section in data.get("slides", []):
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = section.get("slide_title", "Untitled Slide")
        tf = slide.placeholders[1].text_frame
        tf.text = ""

        for line in section.get("main_content", "").split('\n'):
            line = line.strip()
            if not line:
                continue
            p = tf.add_paragraph()
            p.text = line.lstrip('*-1234567890. ')
            p.level = 0
            p.font.size = Pt(18)

        # Add image if available
        image_url = section.get("image_url")
        if image_url:
            try:
                img_data = requests.get(image_url, timeout=10).content
                img_stream = BytesIO(img_data)
                slide.shapes.add_picture(img_stream, Inches(6), Inches(3.5), width=Inches(3))
            except Exception as e:
                txBox = slide.shapes.add_textbox(Inches(6), Inches(3.5), Inches(3), Inches(1))
                txBox.text = f"💡 Image failed: {e}"
        else:
            txBox = slide.shapes.add_textbox(Inches(6), Inches(3.5), Inches(3), Inches(1))
            txBox.text = "💡 " + section.get("image_prompt", "Add relevant image here.")

    prs.save(ppt_path)
    return ppt_path
